# DevSpace configuration for Langfuse observability
version: v2beta1

pipelines:
  dev: |-
    create_deployments --all

deployments:
  langfuse:
    namespace: telemetry
    helm:
      chart:
        path: ./chart
      values:
        # Development-specific values can be added here
        httpRoute:
          # when true, http://langfuse.telemetry.127.0.0.1.nip.io:8080 will be created
          enabled: true
        otelEnvironmentVariableSecrets:
          enabled: true
          namespaces:
            - ark-system
            - default
        demo:
          project:
            publicKey: lf_pk_1234567890
            secretKey: lf_sk_1234567890

hooks:
  - command: |-
      echo "Restarting ark-controller to pick up Langfuse configuration..."
      
      # Check if ark-controller-devspace exists first (DevSpace deployment)
      if kubectl get deployment ark-controller-devspace -n ark-system >/dev/null 2>&1; then
        echo "Found ark-controller-devspace, restarting..."
        kubectl rollout restart deployment/ark-controller-devspace -n ark-system
        kubectl rollout status deployment/ark-controller-devspace -n ark-system --timeout=120s
      # Otherwise check for regular ark-controller deployment
      elif kubectl get deployment ark-controller -n ark-system >/dev/null 2>&1; then
        echo "Found ark-controller, restarting..."
        kubectl rollout restart deployment/ark-controller -n ark-system
        kubectl rollout status deployment/ark-controller -n ark-system --timeout=120s
      else
        echo "Warning: No ark-controller deployment found in ark-system namespace"
      fi
    events: ["after:deploy:langfuse"]
